### ISSUE TITLE
Coins.GetAmountForDenom(denom string) int64

### ISSUE THREAD

**Issue by jaekwon** [tendermint/tmlibs#126]
We should implement GetAmountForDenom(denom string) int64 as a method on Coins, to fetch the amount for a given denom.  Should return 0 if the denom doesn't exist.

**Comment by odeke-em** [comment]
@jaekwon is this the right repo?
Did you mean to open this issue instead for https://github.com/cosmos/cosmos-sdk for this file https://github.com/cosmos/cosmos-sdk/blob/0b5c262f35438e7484b177a410cd4f553632278f/types/coin.go?

**Comment by jaekwon** [comment]
Oh oops, you're right, and it's been implemented.
