### ISSUE TITLE
common: IsHex is fragile if given 0X

### ISSUE THREAD

**Issue by odeke-em** [tendermint/tmlibs#135]
Both 0x and 0X are valid prefixes for hexadecimal except that in our code we only recognize 0x.

https://github.com/tendermint/tmlibs/blob/91b4b534ad78e442192c8175db92a06a51064064/common/string.go#L31-L37

Let's modify that to become
```go
func IsHex(s string) bool { 
 	if len(s) > 2 && strings.EqualFold(s, "0x") { 
 		_, err := hex.DecodeString(s[2:]) 
 		return err == nil 
 	} 
 	return false 
 } 
```
and that should handle the above case too. I mention this as am going through tendermint and any supporting/helper functions to make sure that the perform as intended to.

I think perhaps even my local version of light-client now no longer exists hence we should remove this code.

**Comment by melekes** [comment]
Merged to develop. https://github.com/tendermint/tmlibs/pull/142
