### ISSUE TITLE
glide import failure

### ISSUE THREAD

**Issue by zramsay** [tendermint/tmlibs#148]
i've gotten:
```
[ERROR]	Failed to set version on github.com/tendermint/tmlibs to 15e51fa76086a3c505f227679c2478043ae7261b: Unable to update checked out version: exit status 128
```
several times from various repos over the past week

**Comment by zramsay** [comment]
ethermint, the sdk, etc

**Comment by adrianbrink** [comment]
On the cosmos-sdk this is fixed. On Ethermint I'll try and get to it this weekend.

**Comment by adrianbrink** [comment]
If you notice any others, please let me know.

**Comment by faboweb** [comment]
I can't `glide install` on Gaia as well (commit f08d9cff2737a9886558e1e9b8f660ce9784d774)

**Comment by martindale** [comment]
Bumped into this as well.  Let's switch to tags!

**Comment by ebuchman** [comment]
I beleive this is stale.
