### ISSUE TITLE
Repeat timer quit channel race

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tmlibs#149]
`case <-quit: // NOTE: t.quit races.`

https://github.com/tendermint/tmlibs/blob/develop/common/repeat_timer.go#L163

**Comment by melekes** [comment]
Is this something we need to fix?

**Comment by ebuchman** [comment]
A potential race condition? I would think so.

**Comment by zramsay** [comment]
https://github.com/tendermint/tendermint/issues/1868
