### ISSUE TITLE
common: WriteFileAtomic should not ignore file.Write errors while trying to preserve error before cleanup

### ISSUE THREAD

**Issue by odeke-em** [tendermint/tmlibs#159]
The code for WriteFileAtomic attempts to always cleanup on any error but unfortunately it has a flaw in that it ignores the error from f.Write

https://github.com/tendermint/tmlibs/blob/1b9b5652a199ab0be2e781393fb275b66377309d/common/os.go#L135

We can avoid such by:
a) Making a named error `err` 
b) A defer cleanup routine that'll clean up the created directory if err != nil 

The above will properly handle our conditions and let's also try to return early on errors.

**Comment by odeke-em** [comment]
I discovered while investigating https://github.com/tendermint/tendermint/issues/1290. We are close to launch hence should be more careful with such code plus anything that Tendermint uses.

**Comment by odeke-em** [comment]
Ironically for WriteFileAtomic, if f.Write returns an error, no other error check will be performed because of the error checking style
as per 
https://github.com/tendermint/tmlibs/blob/1b9b5652a199ab0be2e781393fb275b66377309d/common/os.go#L135-L153

**Comment by melekes** [comment]
> it has a flaw in that it ignores the error from f.Write

no, it does not.

**Comment by odeke-em** [comment]
That was poor wording from me, thanks for pointing that out @melekes. It takes the error from f.Write if that occurs but doesn't return immediately thus ignores all the other errors, say if Close , permission errors occur.

**Comment by odeke-em** [comment]
@xla addressed this with https://github.com/tendermint/tmlibs/pull/171.
