### ISSUE TITLE
Flowrate tests fail non-deterministically

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tmlibs#16]
https://circleci.com/gh/tendermint/tmlibs/59

**Comment by melekes** [comment]
Sometimes `time.Sleep` takes more than 100ms

```
clock before sleeping: 0.78
Sleeping for 100ms
clock after sleeping: 0.9
```

**Comment by melekes** [comment]
Don't know how to fix this except not comparing durations. But rates are also different when durations are.

```
                expected: {true 2017-05-23 13:22:55.4 +0000 UTC 400ms 0s 80 4 200 200 200 200 20 100ms 80.000%}
                got     : {true 2017-05-23 13:22:55.4 +0000 UTC 420ms 0s 80 4 200 197 190 200 20 100ms 80.000%}
```

**Comment by melekes** [comment]
https://github.com/tendermint/tmlibs/pull/20#issuecomment-303534296

**Comment by melekes** [comment]
Fixed in https://github.com/tendermint/tmlibs/pull/20/commits/5f20b3323e6afa49eb7c681a953611af08f43206. If it is a bad way and you can think of something else, please tell me

**Comment by adrianbrink** [comment]
Is there a specific reasoning behind these two constants:
```
const maxDeviationForDuration = 50 * time.Millisecond
const maxDeviationForRate int64 = 50
```

If so, we should probably document it.

**Comment by melekes** [comment]
@adrianbrink no. it's basically `{max seen deviation * 2}`
