### ISSUE TITLE
cli: config parse error

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tmlibs#172]
If the config has an error (invalid toml), we get the following message:

```
viper.ConfigParseError{err:(*errors.errorString)(0xc42093ff90)}
```

but otherwise the command runs. It should probably exit instead so we don't run despite a bad config

**Comment by ebuchman** [comment]
Found from https://github.com/tendermint/tendermint/pull/1282#issuecomment-374061521

**Comment by tomc974** [comment]
@ebuchman Looks like it has already been fixed in https://github.com/tendermint/tmlibs/commit/6e26392209cba2758a36fe37f125ecdfc22db5fa
