### ISSUE TITLE
Eliminate Dependency on GCC

### ISSUE THREAD

**Issue by martindale** [tendermint/tmlibs#176]
In preparation for determistic builds, let's consider reducing/eliminating our dependency on GCC.

Considerations:
- Moving CLevelDB to an external process?
- standard external storage API (including Redis, GRPC...)?
- shared memory system?

**Comment by ebuchman** [comment]
https://github.com/tendermint/tendermint/issues/1162

**Comment by zramsay** [comment]
https://github.com/tendermint/tendermint/issues/1870
