### ISSUE TITLE
[log] unsupported value type

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tmlibs#18]
logging fails if we try to use a struct as a value

**Comment by melekes** [comment]
I think this is made intentionally https://github.com/go-logfmt/logfmt/blob/390ab7935ee28ec6b286364bba9b4dd6410cb3d5/encode_test.go#L41 https://github.com/go-logfmt/logfmt/issues/1

**Comment by adrianbrink** [comment]
@ebuchman @melekes Can this be closed as it is not supported or are we going to implement this ourselves?

**Comment by ebuchman** [comment]
Hmmm ... We just need to make sure it's VERY WELL documented. Otherwise folks will be wasting time figuring out why they not getting log statements ...

**Comment by melekes** [comment]
See https://github.com/go-logfmt/logfmt/issues/1#issuecomment-107128569

**Comment by melekes** [comment]
Let's do this: 

```
err := e.EncodeKeyval(k, v)
if err == logfmt.ErrUnsupportedValueType {
    e.EncodeKeyval(k, fmt.Sprintf("%+v", v))
}
```

**Comment by zramsay** [comment]
#77
