### ISSUE TITLE
I want to iterate over database content,  how to decode the content ?

### ISSUE THREAD

**Issue by wadelee1986** [tendermint/tmlibs#184]
exampel: blockstore.db  evidence.db   state.db  trusthistory.db  tx_index.db

how to decode  ?
who can give me a demo ?

**Comment by ebuchman** [comment]
These are ultimately LevelDB files. The content is Tendermint specific. There may be LevelDB tools that help you iterate over the content, so I'd say look there.

If you want to see the Tendermint content, you'd need to load the db like Tendermint does and use code from Tendermint packages to eg read out blocks or state or whatever.
