### ISSUE TITLE
cmn: dont call f.Close() twice in WriteFileAtomic

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tmlibs#192]
Maybe break out a `_writeFileAtomic` which can have a `defer f.Close`. When it returns all we have to do is the rename

**Comment by melekes** [comment]
There is nothing wrong with calling `Close()` twice, except for the fact of calling itself.

**Comment by zramsay** [comment]
https://github.com/tendermint/tendermint/issues/1876
