### ISSUE TITLE
Document to outline possible functions to move in

### ISSUE THREAD

**Issue by rigelrozanski** [tendermint/tmlibs#197]
Generally IMO we want to keep this repo relatively clean/empty of functions which are not explicitly used in multiple other libraries - however it becomes a bit confusing if you were to use a common function for the second time (aka it's not yet in tmlibs) but it's location is a hide and seek round. 

As such I could see it making sense to have a list of possible future functions to move in and their current location - I could see this saving time / avoiding accidental re-implementation.

reference: https://github.com/cosmos/cosmos-sdk/pull/767#discussion_r178670355

**Comment by zramsay** [comment]
re-open in coding repo if still relevant given repo consolidation
