### ISSUE TITLE
Implement SocketDB

### ISSUE THREAD

**Issue by cwgoes** [tendermint/tmlibs#203]
From conversation with @jaekwon -

```
jaekwon - btw we also need to create a socket version of DB so we can connect an external DB… SocketDB.
maybe using GRPC or something.  lmk if you have time to work on it.

cwgoes
I can probably work on SocketDB next week, did you have a particular gRPC interface in mind / should SocketDB include "socketDB server" which interfaces to a local non-socket DB?

jaekwon
yes, and we just need to support CLevelDB there for now.
i don’t have a particular gRPC interface in mind.  I wonder if someone’s already done this work.
it also needs security so we need to be able to do a TLS handshake first… or use secret_connection.

**Comment by ebuchman** [comment]
Looks like Odeke started working on this in https://github.com/tendermint/tmlibs/pull/162.

Theres also already an issue for this in https://github.com/tendermint/tendermint/issues/1162

I suppose we can close that one and let this one track.

**Comment by odeke-em** [comment]
@ebuchman in deed :)

Please feel free to take over it @cwgoes and @ebuchman: my PR allows for authentication and it is over gRPC both with single and bidirectional streaming -- I believe it satisfies all the requested requirements from @jaekwon and @ebuchman, but perhaps could even be tweaked further

**Comment by cwgoes** [comment]
To be added: secure transport layer ([helpful guide](https://bbengfort.github.io/programmer/2017/03/03/secure-grpc.html)).

**Comment by cwgoes** [comment]
Are we OK with https://github.com/square/certstrap as a dependency?

**Comment by cwgoes** [comment]
Do we want batch operations? Presumably...

**Comment by cwgoes** [comment]
Closed by https://github.com/tendermint/tmlibs/pull/162. Still going to attempt CLevelDB deterministic builds.
