### ISSUE TITLE
Change encodeByteSlice to amino.WriteByteSlice

### ISSUE THREAD

**Issue by mossid** [tendermint/tmlibs#205]
[SimpleHashFromTwoHashers](https://github.com/tendermint/tmlibs/blob/master/merkle/simple_tree.go#L31) uses `encodeByteSlice` instead of `amino.WriteByteSlice`. It prepends the length of the string to the child nodes' hash, making it hard to hash in other conditions. 

For example, IAVL hashing uses amino.WriteByteSlice, which just append the two child's hash to make a plain text.

**Comment by ebuchman** [comment]
It's fully compatible with Amino isn't it ? I copied the function because I was trying to remove the dependency in here ... maybe that was bad ?
