### ISSUE TITLE
Maybe A bug in bit_array.go may cause crash

### ISSUE THREAD

**Issue by Hugo-Huang** [tendermint/tmlibs#226]
line 260 in bit_array.go if param bA is nil may cause crash, even though there is a "if bA == nil" in the func StringIndented().  I am confused why the latest version removed the if condition.
[https://github.com/tendermint/tmlibs/blob/master/common/bit_array.go](url)

**Comment by zramsay** [comment]
this repo has been merged into the Tendermint Core repo, see https://github.com/tendermint/tendermint/tree/master/libs and https://github.com/tendermint/tendermint/issues/1952
