### ISSUE TITLE
logger should panic

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tmlibs#29]
Its cool that logging can return errors, but we dont check them anywhere, and we dont want to litter the code with those checks. So maybe we should just panic? Otherwise it can be a pain to find out why logs arent working !

**Comment by melekes** [comment]
This is a good idea from the first glance. What I am afraid of is a user catching a `panic` under some conditions we are not testing. Or it is fine?

```
if A {
  if !B { // no tests for this
    logger.Info("...", " sdfsdf")
  }
}
```

**Comment by melekes** [comment]
Maybe it will be better to have the `panic` feature automatically turned on during testing?

**Comment by ebuchman** [comment]
> What I am afraid of

Good thing to be afraid of. This is where test coverage becomes critical! 

> Maybe it will be better to have the panic feature automatically turned on during testing?

This would be cool too. But doesn't solve anything if we dont have coverage of a particular log statement!


Can we upgrade the logger lib to just handle bad args gracefully instead of throwing ?

**Comment by melekes** [comment]
> Can we upgrade the logger lib to just handle bad args gracefully instead of throwing ?

like log an error from logger using the logger itself? :) yeah, we could do it

**Comment by zramsay** [comment]
fixed in https://github.com/tendermint/tmlibs/commit/65a07b80a33196e063601cb97b51e45dcbd7d66c

**Comment by melekes** [comment]
nope

**Comment by zramsay** [comment]
#76
