### ISSUE TITLE
Add support for other dbs

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tmlibs#30]
- https://github.com/dgraph-io/badger - lightning fast kv store in pure Go

**Comment by odeke-em** [comment]
How about
- [ ] BoltDB

...Add others here

**Comment by melekes** [comment]
There is an issue with too many dependencies. See

https://github.com/tendermint/tmlibs/pull/58#issuecomment-341873935
https://github.com/tendermint/tmlibs/pull/58#issuecomment-341901768
https://github.com/tendermint/tmlibs/pull/58#issuecomment-342107988
