### ISSUE TITLE
db: MemDB's Close code is invalid

### ISSUE THREAD

**Issue by odeke-em** [tendermint/tmlibs#55]
Currently db.MemDB's Close code is
https://github.com/tendermint/tmlibs/blob/9997e3a3b46db1d2f88aa9816ed0e7915dad6ac1/db/mem_db.go#L54-L58

The bug here is us mistakenly setting db to nil expecting the pointer of db to be reflected outside fo that function call.
This code illustrates the problem at https://play.golang.org/p/UebaqWNNJe or inlined
```go
package main

import "fmt"

type DB struct {
	m map[string]interface{}
}

func (db *DB) Set(key string, value interface{}) { db.m[key] = value }
func (db *DB) Get(key string) interface{}        { return db.m[key] }

func (db *DB) properClose() {
	for k := range db.m {
		delete(db.m, k)
	}
}

func (db *DB) buggyClose() {
	db = nil
}

func newDB() *DB { return &DB{m: make(map[string]interface{})} }

func main() {
	db1 := newDB()
	db1.Set("foo", "bar")
	fmt.Printf("Get: %v\n", db1.Get("foo"))
	db1.buggyClose()
	fmt.Printf("After buggy close: %v\n", db1.Get("foo"))
	db1.properClose()
	fmt.Printf("After proper close: %v\n", db1.Get("foo"))
}
```
invoking `db = nil` does nothing since that doesn't actually change the pointer data.

I found this while writing the tests for `tendermint/blockStore`

**Comment by melekes** [comment]
Interesting find!

**Comment by ebuchman** [comment]
Cool thanks!
