### ISSUE TITLE
db: concurrency

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tmlibs#79]
Document that `DB` is a thread safe interface.

- MemDB is thread safe by design (see use of mtx in package)
- GoLevelDB is [documented](https://godoc.org/github.com/syndtr/goleveldb/leveldb) to be thread safe 
- CLevelDB uses github.com/jmhodges/levigo which expects the canonical [LevelDB](https://github.com/google/leveldb) to be installed, which is also thread safe
  - https://github.com/google/leveldb/blob/master/doc/index.md#concurrency
  - Note iterators and batch objects are not themselves thread safe

**Comment by odeke-em** [comment]
Nice! Then later, perhaps for integration tests before releases, we could have some sort of tests that ensure that the documented DBs actually conform to the promise of being concurrency safe.

**Comment by zramsay** [comment]
https://github.com/tendermint/tendermint/issues/1864
