### ISSUE TITLE
Build failure on Windows

### ISSUE THREAD

**Issue by adrianbrink** [tendermint/tmlibs#80]
This [function](https://github.com/tendermint/tmlibs/blob/master/common/os.go#L56) does not build on Windows. This causes all upstream users of this library to not build for Windows.

**Comment by melekes** [comment]
This is fixed on develop.

**Comment by adrianbrink** [comment]
I would leave the issues open until it's on master and just tag them with `fixed-on-develop`. Otherwise it is super hard to see whether something is fixed from just looking at the issue list.
