### ISSUE TITLE
process: data racy code + overwriting exit errors

### ISSUE THREAD

**Issue by odeke-em** [tendermint/tmlibs#81]
I just noticed while auditing code in `tendermint/tendermint` here that `process` has racy code in StartProcess
https://github.com/tendermint/tmlibs/blob/d9525c0fb671204450b160807480e1263053fb20/process/process.go#L48-L65

and also the code that saves the ExitState could use some fixing. On encountering an error we optimistically set the ExitState but unconditionally overwrite it below
https://github.com/tendermint/tmlibs/blob/d9525c0fb671204450b160807480e1263053fb20/process/process.go#L52-L56.

An important question though is if this process package is used by any code, if not perhaps we can make a decision to can it as it is untested, rather than expending energy and time on rewriting and testing it.

/cc @ebuchman @melekes @ethanfrey

**Comment by melekes** [comment]
```
rg "tmlibs/process"
abci/tests/test_app/app.go
12:     "github.com/tendermint/tmlibs/process"
```

we use it in the integration test in abci. I think we can rewrite that test to use `os.Process` and remove this package altogether, no?

**Comment by ebuchman** [comment]
Let's gut it

**Comment by odeke-em** [comment]
Awesome, thank you for the input @melekes and @ebuchman. I'll coordinate gutting it with the replacement of that test code .
