### ISSUE TITLE
undefined: syscall.Kill on windows

### ISSUE THREAD

**Issue by icodezjb** [tendermint/tmlibs#88]
Environment

OS: windows amd_64
Problem Description
error info:
github.com\tendermint\tmlibs\common\os.go:56: undefined: syscall.Kill

tmlibs\common\os.go info:
53: // Kill the running process by sending itself SIGTERM
54: func Kill() error {
55:	pid := os.Getpid()
56:	return syscall.Kill(pid, syscall.SIGTERM)
57: }

can you support windows ?

**Comment by melekes** [comment]
This was fixed in v0.4.1 https://github.com/tendermint/tmlibs/blob/master/CHANGELOG.md#041-november-27-2017

**Comment by melekes** [comment]
We're doing our best to support Windows :)

**Comment by melekes** [comment]
Please reopen this if v0.4.1 does not work for you.

**Comment by icodezjb** [comment]
OK
