### ISSUE TITLE
determine if assert.NoErrorf is really usable or not

### ISSUE THREAD

**Issue by petabytestorage** [tendermint/tmlibs#92]
We had some disagreement or confusion and we suspected but did not yet have time to verify that something changed in stretcher/testify because some errors went away for rudi when he typed ```glide update```.  Anton is still confused about it so we don't know if he typed it but this issue is just to get to the bottom of this which was discussed in this pr before. https://github.com/tendermint/tmlibs/pull/86 @melekes   @ebuchman

**Comment by petabytestorage** [comment]
can you please let us know the resolution @melekes ?

**Comment by melekes** [comment]
function exists. testify dependency was outdated.

**Comment by petabytestorage** [comment]
closing the loop with big props to @melekes  for the knowledge share and @ebuchman for suggesting we improve our communication efficiency by closing the learning loop!
